
Server:
  port: 9003

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: Api_Gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userServiceFallback

        - id: user-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
          filters:
            - name: CircuitBreaker
              args:
                name: contact-service
                fallbackuri: forward:/contactServiceFallback


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  endpoint:
    hystrix:
      stream:
        enabled: true